# Generated by Django 3.1 on 2020-08-24 09:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_auto_20200820_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('object___', django.db.models.manager.Manager()),
            ],
        ),
    ]
