# Generated by Django 3.1 on 2020-09-01 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0005_auto_20200827_0607'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
